name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  formula:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: brew install --formula ./Formula/vv.rb
      - run: brew test vv
