name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  formula:
    runs-on: macos-latest
    steps:
      - run: brew tap geo4orce/tap
      - run: brew install geo4orce/tap/vv
      - run: brew test geo4orce/tap/vv
